require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'defectDetection' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNRearCameraCharacteristicsDisplayMetrics', :path => '../node_modules/react-native-rear-camera-characteristics-display-metrics'

  target 'defectDetectionTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'defectDetection-tvOS' do
  # Pods for defectDetection-tvOS

  target 'defectDetection-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
